//// <auto-generated />
//using HotelListing.API.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace HotelListeing.API.Migrations
//{
//    [DbContext(typeof(HotelListeingDbContext))]
//    [Migration("20221108083233_InitialMigration")]
//    partial class InitialMigration
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("HotelListeing.API.Data.Country", b =>
//            {
//                b.Property<int>("Id")
//                    .ValueGeneratedOnAdd()
//                    .HasColumnType("int");

//                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                b.Property<string>("Name")
//                    .HasColumnType("nvarchar(max)");

//                b.Property<string>("ShortName")
//                    .HasColumnType("nvarchar(max)");

//                b.HasKey("Id");

//                b.ToTable("Countries");
//            });

//            modelBuilder.Entity("HotelListeing.API.Data.Hotel", b =>
//            {
//                b.Property<int>("Id")
//                    .ValueGeneratedOnAdd()
//                    .HasColumnType("int");

//                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                b.Property<string>("Address")
//                    .HasColumnType("nvarchar(max)");

//                b.Property<int>("CountryId")
//                    .HasColumnType("int");

//                b.Property<string>("Name")
//                    .HasColumnType("nvarchar(max)");

//                b.Property<double>("Rating")
//                    .HasColumnType("float");

//                b.HasKey("Id");

//                b.HasIndex("CountryId");

//                b.ToTable("Hotels");
//            });

//            modelBuilder.Entity("HotelListeing.API.Data.Hotel", b =>
//            {
//                b.HasOne("HotelListeing.API.Data.Country", "Country")
//                    .WithMany("Hotels")
//                    .HasForeignKey("CountryId")
//                    .OnDelete(DeleteBehavior.Cascade)
//                    .IsRequired();

//                b.Navigation("Country");
//            });

//            modelBuilder.Entity("HotelListeing.API.Data.Country", b =>
//            {
//                b.Navigation("Hotels");
//            });
//#pragma warning restore 612, 618
//        }
//    }
//}