//// <auto-generated />
//using HotelListing.API.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace HotelListeing.API.Migrations
//{
//    [DbContext(typeof(HotelListeingDbContext))]
//    [Migration("20221108084900_SeeedCounriesAndHotels")]
//    partial class SeeedCounriesAndHotels
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("HotelListeing.API.Data.Country", b =>
//            {
//                b.Property<int>("Id")
//                    .ValueGeneratedOnAdd()
//                    .HasColumnType("int");

//                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                b.Property<string>("Name")
//                    .HasColumnType("nvarchar(max)");

//                b.Property<string>("ShortName")
//                    .HasColumnType("nvarchar(max)");

//                b.HasKey("Id");

//                b.ToTable("Countries");

//                b.HasData(
//                    new
//                    {
//                        Id = 1,
//                        Name = "Jamaica",
//                        ShortName = "JM"
//                    },
//                    new
//                    {
//                        Id = 2,
//                        Name = "Bahama",
//                        ShortName = "BS"
//                    },
//                    new
//                    {
//                        Id = 3,
//                        Name = "Cayman Island",
//                        ShortName = "CI"
//                    });
//            });

//            modelBuilder.Entity("HotelListeing.API.Data.Hotel", b =>
//            {
//                b.Property<int>("Id")
//                    .ValueGeneratedOnAdd()
//                    .HasColumnType("int");

//                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                b.Property<string>("Address")
//                    .HasColumnType("nvarchar(max)");

//                b.Property<int>("CountryId")
//                    .HasColumnType("int");

//                b.Property<string>("Name")
//                    .HasColumnType("nvarchar(max)");

//                b.Property<double>("Rating")
//                    .HasColumnType("float");

//                b.HasKey("Id");

//                b.HasIndex("CountryId");

//                b.ToTable("Hotels");

//                b.HasData(
//                    new
//                    {
//                        Id = 1,
//                        Address = "Negril",
//                        CountryId = 1,
//                        Name = "Sandals Resort and Spa",
//                        Rating = 4.5
//                    },
//                    new
//                    {
//                        Id = 2,
//                        Address = "George Town",
//                        CountryId = 3,
//                        Name = "Comfort Suites",
//                        Rating = 4.4000000000000004
//                    },
//                    new
//                    {
//                        Id = 3,
//                        Address = "Nassua",
//                        CountryId = 2,
//                        Name = "Grand Oalldium",
//                        Rating = 4.2999999999999998
//                    });
//            });

//            modelBuilder.Entity("HotelListeing.API.Data.Hotel", b =>
//            {
//                b.HasOne("HotelListeing.API.Data.Country", "Country")
//                    .WithMany("Hotels")
//                    .HasForeignKey("CountryId")
//                    .OnDelete(DeleteBehavior.Cascade)
//                    .IsRequired();

//                b.Navigation("Country");
//            });

//            modelBuilder.Entity("HotelListeing.API.Data.Country", b =>
//            {
//                b.Navigation("Hotels");
//            });
//#pragma warning restore 612, 618
//        }
//    }
//}